---
name: Git Flow Enforcement

on:
  push:
    branches-ignore:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - 'develop'

jobs:
  enforce-git-flow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/requirements/requirements.txt

      - name: Enforce Git Flow
        run: python .github/scripts/git_flow.py main develop feature/ bugfix/ release/ hotfix/ support/ 'v' ''
